const SectorData = [
    {
      state_id: "1",
      sortname: "Mp",
      state_name: "Madhyapradesh",
      budget: [
        {
          budgetNo: "1235",
          statename: "Madhyapradesh",
          Discription:
            "Madhya Pradesh is a state in central India. Its capital is Bhopal, and the largest city is Indore, with Jabalpur, Ujjain, Gwalior, Sagar, Satna, Narmadapuram, Shahdol, Rewa and Morena being the other major cities... ",
          FamousPlace: "Kuchbhi",
        },
      ],
      District: [
        {
          District_id: "1",
          District_name: "khargone",
          satate_id: "1",
          District_info:
            "Khargone district is situated on the south west border of Madhya Pradesh.  Its area is approximately 8030 sq. Km. Dhar, Indore and Dewas are located in the North side of this district. Maharashtra in the South, Khandwa & Burhanpur in the East and Barwani in the West. Located in the central part of the Narmada Valley, north of this district there are Vindhyachal and Satpura mountain ranges in the south.",
          area: "6477.89 Sq. Km.",
          population: "18,72,413",
          language: "Hindi, Nimadi, Gujrati, Bareli",
          Villages: "1421",
            tehsil: [
            /* -----------------------------------------------------------*/
            {
              tehsil_id: "1",
              tehsil_name: "Barwaha",
              District_id: "1",
              villages: [
                {
                  village_id: "1",
                  village_name: "Agar Gaon",
                  tehsil_id: "1",
                  village_budget: "12764",
                  village_population:"12345678",
                },
                {
                  village_id: "2",
                  village_name: "Agarwara",
                  tehsil_id: "1",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "3",
                  village_name: "Akaya",
                  tehsil_id: "1",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "4",
                  village_name: "Ali Bujurg",
                  tehsil_id: "1",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "5",
                  village_name: "Ali Khurd",
                  tehsil_id: "1",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "6",
                  village_name: "Amalatha",
                  tehsil_id: "1",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "7",
                  village_name: "Amarpura",
                  tehsil_id: "1",
                  village_budget: "12764",
                  village_population:"1234567",
                },
                {
                  village_id: "8",
                  village_name: "Amba",
                  tehsil_id: "1",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "9",
                  village_name: "Amjrud",
                  tehsil_id: "1",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "10",
                  village_name: "Aroda",
                  tehsil_id: "1",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "11",
                  village_name: "Arri",
                  tehsil_id: "1",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "12",
                  village_name: "Arsi Mirjapura",
                  tehsil_id: "1",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "13",
                  village_name: "Astaria",
                  tehsil_id: "1",
                  village_budget: "12764",
                  village_population:"1234567",
                },
                {
                  village_id: "14",
                  village_name: "Atarsumba",
                  tehsil_id: "1",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "15",
                  village_name: "Athwan",
                  tehsil_id: "1",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "16",
                  village_name: "Baddiya Khurd",
                  tehsil_id: "1",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "17",
                  village_name: "Badel",
                  tehsil_id: "1",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "18",
                  village_name: "Badgaon",
                  tehsil_id: "1",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "19",
                  village_name: "Badiyabujurag",
                  tehsil_id: "1",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "20",
                  village_name: "Badud",
                  tehsil_id: "1",
                  village_budget: "15364",
                  village_population:"1234567",
                },
              ],
            },
            {
              tehsil_id: "2",
              tehsil_name: "Bhagwanpura",
              District_id: "1",
              villages: [
                {
                  village_id: "1",
                  village_name: "Amba",
                  tehsil_id: "2",
                  village_budget: "12964",
                  village_population:"1234567",
                },
                {
                  village_id: "2",
                  village_name: "Ambakheda",
                  tehsil_id: "2",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "3",
                  village_name: "Amlyapani",
                  tehsil_id: "2",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "4",
                  village_name: "Anakwadi",
                  tehsil_id: "2",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "5",
                  village_name: "Anjengaon",
                  tehsil_id: "2",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "6",
                  village_name: "Badi",
                  tehsil_id: "2",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "7",
                  village_name: "Badi Bujurg",
                  tehsil_id: "2",
                  village_budget: "12764",
                  village_population:"1234567",
                },
                {
                  village_id: "8",
                  village_name: "Badi khurd",
                  tehsil_id: "2",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "9",
                  village_name: "Badya",
                  tehsil_id: "2",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "10",
                  village_name: "Bagadara",
                  tehsil_id: "2",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "11",
                  village_name: "Bagdari",
                  tehsil_id: "2",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "12",
                  village_name: "Bahadarpura",
                  tehsil_id: "2",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "13",
                  village_name: "Balkhad Bujurg",
                  tehsil_id: "2",
                  village_budget: "12764",
                  village_population:"1234567",
                },
                {
                  village_id: "14",
                  village_name: "Balkhad khurd",
                  tehsil_id: "2",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "15",
                  village_name: "Balwadi",
                  tehsil_id: "2",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "16",
                  village_name: "Banganga",
                  tehsil_id: "2",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "17",
                  village_name: "Banher",
                  tehsil_id: "2",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "18",
                  village_name: "Banhur",
                  tehsil_id: "2",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "19",
                  village_name: "Banskhedi",
                  tehsil_id: "2",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "20",
                  village_name: "Bawli",
                  tehsil_id: "2",
                  village_budget: "15364",
                  village_population:"1234567",
                },
              ],
            },
            {
              tehsil_id: "3",
              tehsil_name: "Bhikangaon",
              District_id: "1",
              villages: [
                {
                  village_id: "1",
                  village_name: "Aawaliya",
                  tehsil_id: "3",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "2",
                  village_name: "Ahir Kheda",
                  tehsil_id: "3",
                  village_budget: "12764",
                  village_population:"1234567",
                },
                {
                  village_id: "3",
                  village_name: "Akhapura",
                  tehsil_id: "3",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "4",
                  village_name: "Aman Khedi",
                  tehsil_id: "3",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "5",
                  village_name: "Andad",
                  tehsil_id: "3",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "6",
                  village_name: "Anjangaon",
                  tehsil_id: "3",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "7",
                  village_name: "Aurangpura",
                  tehsil_id: "3",
                  village_budget: "12764",
                  village_population:"1234567",
                },
                {
                  village_id: "8",
                  village_name: "Badgaon",
                  tehsil_id: "3",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "9",
                  village_name: "Badiya",
                  tehsil_id: "3",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "10",
                  village_name: "Balkhadya",
                  tehsil_id: "3",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "11",
                  village_name: "Bamnala",
                  tehsil_id: "3",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "12",
                  village_name: "Banjari",
                  tehsil_id: "3",
                  village_budget: "12764",
                  village_population:"1234567",
                },
                {
                  village_id: "13",
                  village_name: "Banjhar",
                  tehsil_id: "3",
                  village_budget: "12764",
                  village_population:"1234567",
                },
                {
                  village_id: "14",
                  village_name: "Basantpura",
                  tehsil_id: "3",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "15",
                  village_name: "Bhagur",
                  tehsil_id: "3",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "16",
                  village_name: "Bhagwanpura",
                  tehsil_id: "3",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "17",
                  village_name: "Bhatalpura",
                  tehsil_id: "3",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "18",
                  village_name: "Bhikangaon",
                  tehsil_id: "3",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "19",
                  village_name: "Bhopada",
                  tehsil_id: "3",
                  village_budget: "15364",
                  village_population:"1234567",
                },
                {
                  village_id: "20",
                  village_name: "Bhopatpura",
                  tehsil_id: "3",
                  village_budget: "15364",
                  village_population:"1234567",
                },
              ],
            },
            {
              tehsil_id: "4",
              tehsil_name: "Gogaon",
              District_id: "1",
              villages: [
                { village_id: "1", village_name: "Agarbai", tehsil_id: "4" },
                { village_id: "2", village_name: "Amba Deola", tehsil_id: "4" },
                {
                  village_id: "3",
                  village_name: "Atarli",
                  tehsil_id: "4",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "4",
                  village_name: "Awali Bistan",
                  tehsil_id: "4",
                  village_budget:"12345",
                  village_population:"1234567",
                },
                {
                  village_id: "5",
                  village_name: "Badgaon Nagjhiri",
                  tehsil_id: "4",
                  village_budget: "15464",
                  village_population:"1234567",
                },
                {
                  village_id: "6",
                  village_name: "Badgaon Signur",
                  tehsil_id: "4",
                  village_budget: "15464",
                  village_population:"1234567",
                },
                {
                  village_id: "7",
                  village_name: "Baijapura Surpala",
                  tehsil_id: "4",
                  village_budget: "12764",
                  village_population:"1234567",
                },
                {
                  village_id: "8",
                  village_name: "Balabad",
                  tehsil_id: "4",
                  village_budget: "12464",
                },
                {
                  village_id: "9",
                  village_name: "Balapur",
                  tehsil_id: "4",
                  village_budget: "12464",
                },
                {
                  village_id: "10",
                  village_name: "Balgaon",
                  tehsil_id: "4",
                  village_budget: "12464",
                },
                {
                  village_id: "11",
                  village_name: "Behrampura ",
                  tehsil_id: "4",
                  village_budget: "15464",
                },
                {
                  village_id: "12",
                  village_name: "Bheelkheda",
                  tehsil_id: "4",
                  village_budget: "12764",
                },
                {
                  village_id: "13",
                  village_name: "Bid",
                  tehsil_id: "4",
                  village_budget: "12764",
                },
                {
                  village_id: "14",
                  village_name: "Bijalgaon khurd",
                  tehsil_id: "4",
                  village_budget: "12464",
                },
                {
                  village_id: "15",
                  village_name: "Bilali",
                  tehsil_id: "4",
                  village_budget: "12464",
                },
                {
                  village_id: "16",
                  village_name: "Bilkheda",
                  tehsil_id: "4",
                  village_budget: "12464",
                },
                {
                  village_id: "17",
                  village_name: "Bistan",
                  tehsil_id: "4",
                  village_budget: "15464",
                },
                {
                  village_id: "18",
                  village_name: "Borgoan Bilkheda",
                  tehsil_id: "4",
                  village_budget: "15464",
                },
                {
                  village_id: "19",
                  village_name: "Budaya",
                  tehsil_id: "4",
                  village_budget: "15464",
                },
                {
                  village_id: "20",
                  village_name: "Chari",
                  tehsil_id: "4",
                  village_budget: "15464",
                },
              ],
            },
            {
              tehsil_id: "5",
              tehsil_name: "Jhiranya",
              District_id: "1",
              villages: [
                { village_id: "1", village_name: "Abhapuri", tehsil_id: "5" },
                {
                  village_id: "2",
                  village_name: "Abhapuri NanKhodi",
                  tehsil_id: "5",
                },
                {
                  village_id: "3",
                  village_name: "Agasya",
                  tehsil_id: "5",
                  village_budget: "12365",
                },
                {
                  village_id: "4",
                  village_name: "Ambadochar",
                  tehsil_id: "5",
                  village_budget: "12365",
                },
                {
                  village_id: "5",
                  village_name: "Ardla ",
                  tehsil_id: "5",
                  village_budget: "15565",
                },
                {
                  village_id: "6",
                  village_name: "Badi",
                  tehsil_id: "5",
                  village_budget: "15565",
                },
                {
                  village_id: "7",
                  village_name: "Bagdari",
                  tehsil_id: "5",
                  village_budget: "12765",
                },
                {
                  village_id: "8",
                  village_name: "Balkhad",
                  tehsil_id: "5",
                  village_budget: "12565",
                },
                {
                  village_id: "9",
                  village_name: "Baykheda",
                  tehsil_id: "5",
                  village_budget: "12565",
                },
                {
                  village_id: "10",
                  village_name: "Bedchha",
                  tehsil_id: "5",
                  village_budget: "12565",
                },
                {
                  village_id: "11",
                  village_name: "Bedhanaya Khurd",
                  tehsil_id: "5",
                  village_budget: "15565",
                },
                {
                  village_id: "12",
                  village_name: "Bedhanya Buzurg",
                  tehsil_id: "5",
                  village_budget: "12765",
                },
                {
                  village_id: "13",
                  village_name: "Bhadlen",
                  tehsil_id: "5",
                  village_budget: "12765",
                },
                {
                  village_id: "14",
                  village_name: "Bharadi",
                  tehsil_id: "5",
                  village_budget: "12565",
                },
                {
                  village_id: "15",
                  village_name: "Bhavsingh pura",
                  tehsil_id: "5",
                  village_budget: "12565",
                },
                {
                  village_id: "16",
                  village_name: "Bilkhed",
                  tehsil_id: "5",
                  village_budget: "12565",
                },
                {
                  village_id: "17",
                  village_name: "Bondranya",
                  tehsil_id: "5",
                  village_budget: "15565",
                },
                {
                  village_id: "18",
                  village_name: "Borkheda",
                  tehsil_id: "5",
                  village_budget: "15565",
                },
                {
                  village_id: "19",
                  village_name: "Borwal",
                  tehsil_id: "5",
                  village_budget: "15565",
                },
                {
                  village_id: "20",
                  village_name: "Brahman puri",
                  tehsil_id: "5",
                  village_budget: "15565",
                },
              ],
            },
            {
              tehsil_id: "6",
              tehsil_name: "Kasrawad",
              District_id: "1",
              villages: [
                {
                  village_id: "1",
                  village_name: "Adalpura",
                  tehsil_id: "6",
                  village_budget: "12365",
                },
                {
                  village_id: "2",
                  village_name: "Aghanwan",
                  tehsil_id: "6",
                  village_budget: "12365",
                },
                {
                  village_id: "3",
                  village_name: "Ahilyapura",
                  tehsil_id: "6",
                  village_budget: "12366",
                },
                {
                  village_id: "4",
                  village_name: "Akbarpura",
                  tehsil_id: "6",
                  village_budget: "12366",
                },
                {
                  village_id: "5",
                  village_name: "Amlatha",
                  tehsil_id: "6",
                  village_budget: "1666",
                },
                {
                  village_id: "6",
                  village_name: "Aurangapura",
                  tehsil_id: "6",
                  village_budget: "1666",
                },
                {
                  village_id: "7",
                  village_name: "Aurangpura",
                  tehsil_id: "6",
                  village_budget: "12766",
                },
                {
                  village_id: "8",
                  village_name: "Awalya",
                  tehsil_id: "6",
                  village_budget: "1166",
                },
                {
                  village_id: "9",
                  village_name: "Awarkachh",
                  tehsil_id: "6",
                  village_budget: "12666",
                },
                {
                  village_id: "10",
                  village_name: "Badgaon",
                  tehsil_id: "6",
                  village_budget: "12666",
                },
                {
                  village_id: "11",
                  village_name: "Badi",
                  tehsil_id: "6",
                  village_budget: "1666",
                },
                {
                  village_id: "12",
                  village_name: "Badya",
                  tehsil_id: "6",
                  village_budget: "12766",
                },
                {
                  village_id: "13",
                  village_name: "Bahadarpura",
                  tehsil_id: "6",
                  village_budget: "12766",
                },
                {
                  village_id: "14",
                  village_name: "Bahaderpura",
                  tehsil_id: "6",
                  village_budget: "12666",
                },
                {
                  village_id: "15",
                  village_name: "Baigandi",
                  tehsil_id: "6",
                  village_budget: "12666",
                },
                {
                  village_id: "16",
                  village_name: "Bairagarh",
                  tehsil_id: "6",
                  village_budget: "12666",
                },
                {
                  village_id: "17",
                  village_name: "Bajitpura",
                  tehsil_id: "6",
                  village_budget: "1666",
                },
                {
                  village_id: "18",
                  village_name: "Balakwada",
                  tehsil_id: "6",
                  village_budget: "1666",
                },
                {
                  village_id: "19",
                  village_name: "Balgaon",
                  tehsil_id: "6",
                  village_budget: "1666",
                },
                {
                  village_id: "20",
                  village_name: "Balkhad",
                  tehsil_id: "6",
                  village_budget: "1666",
                },
              ],
            },
            {
              tehsil_id: "7",
              tehsil_name: "Khargone",
              District_id: "1",
              villages: [
                {
                  village_id: "1",
                  village_name: "Aarampura",
                  tehsil_id: "7",
                  village_budget: "12366",
                },
                {
                  village_id: "2",
                  village_name: "Adampura",
                  tehsil_id: "7",
                  village_budget: "12366",
                },
                {
                  village_id: "3",
                  village_name: "Aghawan",
                  tehsil_id: "7",
                  village_budget: "1237",
                },
                {
                  village_id: "4",
                  village_name: "Akawalya",
                  tehsil_id: "7",
                  village_budget: "1237",
                },
                {
                  village_id: "5",
                  village_name: "Asangaon",
                  tehsil_id: "7",
                  village_budget: "17",
                },
                {
                  village_id: "6",
                  village_name: "Awali",
                  tehsil_id: "7",
                  village_budget: "17",
                },
                {
                  village_id: "7",
                  village_name: "Badya",
                  tehsil_id: "7",
                  village_budget: "1277",
                },
                {
                  village_id: "8",
                  village_name: "Baghwa",
                  tehsil_id: "7",
                  village_budget: "127",
                },
                {
                  village_id: "9",
                  village_name: "Bagud",
                  tehsil_id: "7",
                  village_budget: "127",
                },
                {
                  village_id: "10",
                  village_name: "Bahadurpura",
                  tehsil_id: "7",
                  village_budget: "127",
                },
                {
                  village_id: "11",
                  village_name: "Baijapura",
                  tehsil_id: "7",
                  village_budget: "17",
                },
                {
                  village_id: "12",
                  village_name: "Balwadi Soniipura",
                  tehsil_id: "7",
                  village_budget: "1277",
                },
                {
                  village_id: "13",
                  village_name: "Banjari",
                  tehsil_id: "7",
                  village_budget: "1277",
                },
                {
                  village_id: "14",
                  village_name: "Bardiya",
                  tehsil_id: "7",
                  village_budget: "127",
                },
                {
                  village_id: "15",
                  village_name: "Barkheda",
                  tehsil_id: "7",
                  village_budget: "127",
                },
                {
                  village_id: "16",
                  village_name: "Barud",
                  tehsil_id: "7",
                  village_budget: "127",
                },
                {
                  village_id: "17",
                  village_name: "Bediyapura",
                  tehsil_id: "7",
                  village_budget: "17",
                },
                {
                  village_id: "18",
                  village_name: "Belmar",
                  tehsil_id: "7",
                  village_budget: "17",
                },
                {
                  village_id: "19",
                  village_name: "Bhamori Buzurg",
                  tehsil_id: "7",
                  village_budget: "17",
                },
                {
                  village_id: "20",
                  village_name: "Bhamori",
                  tehsil_id: "7",
                  village_budget: "17",
                },
              ],
            },
            {
              tehsil_id: "8",
              tehsil_name: "Maheshwar",
              District_id: "1",
              villages: [
                { village_id: "1", village_name: "Ahilypura", tehsil_id: "8" },
                { village_id: "2", village_name: "Ajitpura", tehsil_id: "8" },
                {
                  village_id: "3",
                  village_name: "Akhipura",
                  tehsil_id: "8",
                  village_budget: "11764",
                },
                {
                  village_id: "4",
                  village_name: "Ashapur",
                  tehsil_id: "8",
                  village_budget: "13764",
                },
                {
                  village_id: "5",
                  village_name: "Asukhedi",
                  tehsil_id: "8",
                  village_budget: "14764",
                },
                {
                  village_id: "6",
                  village_name: "Awalya",
                  tehsil_id: "8",
                  village_budget: "15764",
                },
                {
                  village_id: "7",
                  village_name: "Bablai",
                  tehsil_id: "8",
                  village_budget: "10764",
                },
                {
                  village_id: "8",
                  village_name: "Bada",
                  tehsil_id: "8",
                  village_budget: "10764",
                },
                {
                  village_id: "9",
                  village_name: "Badadiya surta",
                  tehsil_id: "8",
                  village_budget: "10764",
                },
                {
                  village_id: "10",
                  village_name: "Baddiya",
                  tehsil_id: "8",
                  village_budget: "10764",
                },
                {
                  village_id: "11",
                  village_name: "Badwel",
                  tehsil_id: "8",
                  village_budget: "10764",
                },
                {
                  village_id: "12",
                  village_name: "Badwi",
                  tehsil_id: "8",
                  village_budget: "10764",
                },
                {
                  village_id: "13",
                  village_name: "Bagkeria khedi",
                  tehsil_id: "8",
                  village_budget: "10764",
                },
                {
                  village_id: "14",
                  village_name: "Bagsomakhedi",
                  tehsil_id: "8",
                  village_budget: "10764",
                },
                {
                  village_id: "15",
                  village_name: "Bahegawan",
                  tehsil_id: "8",
                  village_budget: "10764",
                },
                {
                  village_id: "16",
                  village_name: "Bakaner",
                  tehsil_id: "8",
                  village_budget: "10764",
                },
                {
                  village_id: "17",
                  village_name: "Balasgaon",
                  tehsil_id: "8",
                  village_budget: "10764",
                },
                {
                  village_id: "18",
                  village_name: "Bandera",
                  tehsil_id: "8",
                  village_budget: "10764",
                },
                {
                  village_id: "19",
                  village_name: "Banjari",
                  tehsil_id: "8",
                  village_budget: "10764",
                },
                {
                  village_id: "20",
                  village_name: "Bardiya",
                  tehsil_id: "8",
                  village_budget: "10764",
                },
              ],
            },
            {
              tehsil_id: "9",
              tehsil_name: "Segaon",
              District_id: "1",
              villages: [
                { village_id: "1", village_name: "Achhalwadi", tehsil_id: "9" },
                { village_id: "2", village_name: "Badha", tehsil_id: "9" },
                { village_id: "3", village_name: "Baneehar", tehsil_id: "9" },
                { village_id: "4", village_name: "Bhadwali", tehsil_id: "9" },
                { village_id: "5", village_name: "Bhikharkhedi", tehsil_id: "9" },
                { village_id: "6", village_name: "Birla", tehsil_id: "9" },
                { village_id: "7", village_name: "Bori", tehsil_id: "9" },
                { village_id: "8", village_name: "Chandawad", tehsil_id: "9" },
                { village_id: "9", village_name: "Chhipeepura", tehsil_id: "9" },
                { village_id: "10", village_name: "Chichgarh", tehsil_id: "9" },
                { village_id: "11", village_name: "Chichli", tehsil_id: "9" },
                { village_id: "12", village_name: "Dalki", tehsil_id: "9" },
                { village_id: "13", village_name: "Damkheda", tehsil_id: "9" },
                { village_id: "14", village_name: "Dasnawal", tehsil_id: "9" },
                { village_id: "15", village_name: "Deoli", tehsil_id: "9" },
                { village_id: "16", village_name: "Domwada", tehsil_id: "9" },
                { village_id: "17", village_name: "Gandhawad", tehsil_id: "9" },
                { village_id: "18", village_name: "Gatlakhedi", tehsil_id: "9" },
                { village_id: "19", village_name: "Golpura", tehsil_id: "9" },
                { village_id: "20", village_name: "Golwadi", tehsil_id: "9" },
                { village_id: "21", village_name: "Gyaspura", tehsil_id: "9" },
                { village_id: "22", village_name: "Hanumantya", tehsil_id: "9" },
              ],
            },
  
            /* -----------------------------------------------------------*/
            //     {"tehsil_id":"1","tehsil_name":"maheshwer","District_id":"1", "villages": [
            //         {"village_id":"1","village_name":"Ahilypura","tehsil_id":"1","village_budget":"12764"},
            //         {"village_id":"2","village_name":"Ajitpura","tehsil_id":"1" ,"village_budget":"22764"},
            //         {"village_id":"3","village_name":"Akhipura","tehsil_id":"1","village_budget":"11764"},
            //         {"village_id":"4","village_name":"Ashapur","tehsil_id":"1","village_budget":"13764"},
            //         {"village_id":"5","village_name":"Asukhedi","tehsil_id":"1","village_budget":"14764"},
            //         {"village_id":"6","village_name":"Awalya","tehsil_id":"1","village_budget":"15764"},
            //         {"village_id":"7","village_name":"Bablai","tehsil_id":"1","village_budget":"10764"},
  
            //     ]},
            //     {"tehsil_id":"2","tehsil_name":"kasrawad","District_id":"1", "villages": [
            //         {"village_id":"1","village_name":"borawan","tehsil_id":"1"},
            //         {"village_id":"2","village_name":"hi","tehsil_id":"1"},
            //     ]}
          ],
        },
        {
          District_id: "2",
          District_name: "Barwani",
          District_info: "Barwani is situated on the southern west side of Madhya Pradesh as well as holy river Narmada. District is surrounded by Satpuda (in South) and Vindhyachal (in North) forest ranges.",
          area: "5,427 Sq. Km.",
          population: "13,85,881",
          language: "Hindi And Nimari",
          state_id: "1",
          tehsil: [
            {
              tehsil_id: "1",
              tehsil_name: "Anjad",
              District_id: "2",
              villages: [
                { village_id: "1", village_name: "Anjad", tehsil_id: "1" },
                { village_id: "2", village_name: "Awali", tehsil_id: "1" },
              ],
            },
            {
              tehsil_id: "2",
              tehsil_name: "Thikri",
              District_id: "2",
              villages: [
                { village_id: "1", village_name: "Abhali", tehsil_id: "2" },
                { village_id: "2", village_name: "Ajandi", tehsil_id: "2" },
              ],
            },
            {
              tehsil_id: "3",
              tehsil_name: "Rajpur",
              District_id: "2",
              villages: [
                { village_id: "1", village_name: "Agalgaon", tehsil_id: "3" },
                { village_id: "2", village_name: "Atarsanbha", tehsil_id: "3" },
              ],
            },
            {
              tehsil_id: "4",
              tehsil_name: "Sendhwa",
              District_id: "2",
              villages: [
                { village_id: "1", village_name: "Achhali", tehsil_id: "4" },
                { village_id: "2", village_name: "Amjhiri", tehsil_id: "4" },
              ],
            },
          ],
        },
      ],
    },
  
    {
      state_id: "2",
      sortname: "MH",
      state_name: "Maharashtra",
      budget: [
        {
          budgetNo: "1235786",
          Discription:"Maharashtra is a leader among Indian states in terms of agricultural and industrial production, trade and transport, and education. Its ancient culture, at one stage considerably obscured by British dominance, survives largely through the medium of a strong literary heritage",
         
        },
      ],
      District: [
        {
          District_id: "1",
          District_name: "Pune",
          satate_id: "2",
          tehsil: [
            {
              tehsil_id: "1",
              tehsil_name: "maheshwer",
              District_id: "1",
              villages: [
                { village_id: "1", village_name: "Ahilypura", tehsil_id: "1" },
                { village_id: "2", village_name: "Ajitpura", tehsil_id: "1" },
                { village_id: "3", village_name: "Akhipura", tehsil_id: "1" },
                { village_id: "4", village_name: "Ashapur", tehsil_id: "1" },
                { village_id: "5", village_name: "Asukhedi", tehsil_id: "1" },
                { village_id: "6", village_name: "Awalya", tehsil_id: "1" },
                { village_id: "7", village_name: "Bablai", tehsil_id: "1" },
              ],
            },
            {
              tehsil_id: "2",
              tehsil_name: "kasrawad",
              District_id: "1",
              villages: [
                { village_id: "1", village_name: "borawan", tehsil_id: "1" },
                { village_id: "2", village_name: "hi", tehsil_id: "1" },
              ],
            },
          ],
        },
        {
          District_id: "2",
          District_name: "Nagpur",
          state_id: "1",
          tehsil: [
            {
              tehsil_id: "1",
              tehsil_name: "anjad",
              District_id: "2",
              villages: [
                { village_id: "1", village_name: "hello", tehsil_id: "1" },
                { village_id: "2", village_name: "khushi", tehsil_id: "1" },
              ],
            },
            {
              tehsil_id: "2",
              tehsil_name: "thikri",
              District_id: "1",
              villages: [
                { village_id: "1", village_name: "hiii", tehsil_id: "2" },
                { village_id: "2", village_name: "hi", tehsil_id: "2" },
              ],
            },
          ],
        },
      ],
    },
    {
      state_id: "3",
      sortname: "Ap",
      state_name: "Andrapradesh",
      budget: [
        {
          budgetNo: "1235789",
          Discription:
            "Uttar Pradesh is a state in northern India. With over 240 million inhabitants, it is the most populated state in India as well as the most populous country subdivision in the world. It was established in 1950 after India had become a republic. It was a successor to the United Provinces (UP) during the period of the ",
          FamousPlace: "Kuchbhi01",
        },
      ],
    },
  
    {
      state_id: "4",
      sortname: "Ap",
      state_name: "Andrapradesh",
      budget: [
        {
          budgetNo: "1235789",
          Discription:
            "Uttar Pradesh is a state in northern India. With over 240 million inhabitants, it is the most populated state in India as well as the most populous country subdivision in the world. It was established in 1950 after India had become a republic. It was a successor to the United Provinces (UP) during the period of the ",
          FamousPlace: "Kuchbhi01",
        },
      ],
    },
  ];
  export default SectorData;