const PageData =
[
  { title:'Success Story Of Madhya Pradesh',
    heading:'Better model of water management, Bichiya Lift Irrigation Scheme',
    content1:'The rural economy of Shahdol district is dependent onagriculture, water is an important component for agriculture, if water is available to the farmer as per the requirement ontime for crop irrigation, then the crop production automatically increases and the farmer can use every drop ofwater. One starts keeping accounts, the example of which canbe obtained from the lift irrigation scheme built on the stop dam in Vichia village. In the year 1991-1992, a stop dam was built by the Rural Engineering Department for the purpose ofirrigation of agriculture and common disposal in Jamua Nala flowing in village Bichiya of Budhar Janpad Panchayat of Shahdol district. People of tribal caste live in Bichiya village, these poor farmers did not have enough capital of their own to use the water collected in the stop dam through electric or diesel pump to lift it to their fields.',
    content2:' Due to which they were dependent on rain water. But the lack of water for irrigation definitely hurt them. In the year 2002, after taking a decision by the District Panchayat, a special campaign was launched to select liftable irrigation sources. During the campaign, the villagers applied to the Assistant Extension Officer of that area to arrange forirrigation facilities by showing the accumulated water in the stop dam. A.D.O. The villagers were advised to form a group byorganizing 14 tribal farmers coming under the irrigation area.The villagers formed their own group and unanimously elected Mr. Loknath Singh as the president.After this A.D.O. UnderSwarna Jayanti Gram Swarozgar Yojana, a case was prepared andsent to the bank for lift irrigation scheme. A loan and grantof Rs 1.65 lakh was sanctioned from the bank. In which Rs 94 thousand was grant and Rs 71 thousand was loan. With thisamount, the farmers constructed drains in the pump house fields and bought two electric pumps. Now the problem was the power line. Which the Chief Executive Officer of the District Panchayat made available funds to the Electricity Department from the sub-structure head of Swarna Jayanti Gram Swarozgar Yojana and took the power line to the pump house. As soon as the problem of electricity was solved, the farmers lifted the water from the stop dam and brought it to their fields. In the district, on February 2, 2002, when the Chief Secretary of the Panchayat Rural Development Department visited the Jal district to inquire about the operation of the schemes of the Rural Development Department, then Mr. Loknath Singh, the chairman of the group of Vichia Lift Irrigation Scheme, said that Sir, my luck Changed Now we all operate it on the basis of mutual decision and deliver water to our fields as per requirement.',
    content3:' After the start of this scheme, 19.4 hectares of land of the group members is being irrigated and where earlier we used to take Kodo, Kutki crops, today we have started taking best quality paddy and wheat crops. If there is more water than required, they earn extra income by irrigating others fields on rent, keeping the received amount accumulated, they do it for meeting electricity bills and other incidental expenses.This year we have produced double the crop. This first year was a new experience for us members. Now all of us farmers will not have to depend on natures rain, there is enough water for our use. We all have understood this. From next year, we will start getting bank loans by cultivating vegetables in summer. Hearing this, the Principal Secretary was very happy and advised to motivate other nearby villagers to take advantage of similar schemes.',
     image:'https://picsum.photos/200',  
     image1:'https://picsum.photos/200', 
  },
  {
    title:'Success Story Of Madhya Pradesh',
    heading:'Moving towards financial independence. Awakening Women Self Help Group of Village Balbahara.',
    content1:"There is great power in unity, this has been proved by the women of awakened self-help group of Balvahara village of Budhar district panchayat. In the year 1999, women united with the inspiration of the supervisor of women and child development, formed a 15-member women's savings group and started saving 30 rupees monthly by saving from their daily expenses. All these women used to do domestic work, due to which they had to depend on their husbands for savings, due to which the women met and expressed their desire to do some business and also passed a resolution in the meeting register. The information about his proposal was conveyed to the Chief Executive Officer of the District Panchayat through the Chief Executive Officer of the District Panchayat. Chief Executive Officer, District Panchayat directed to do the first grading of the group, in which the group was also successful. Thereafter, the revolving fund was made available to the group by the District Panchayat. On the basis of mutual decision, the group used this amount as a loan for their necessary works, which got them freedom from the co-operative system. In the year 2000, the District Panchayat decided to supply nutritional food (porridge production) to the Anganwadi centers run by the Women and Child Development Department through women's savings groups. The information about this decision was given to the members of Jagriti Self Help Group. Thirteen members of the group expressed their consent to engage in the porridge production work. The members of the group lacked capital to start the work and lack of knowledge about the working method of porridge production. ",
    content2:"Mrs. Munni Pav, President of the Women's Self Help Group, says that in view of the eagerness of the members of the group, we contacted the Assistant Extension Officer of the Rural Development Department and after preparing our case under the Swarna Jayanti Gram Swarozgar Yojana run by the government, Shahdol Regional Rural Sent to Bank Chachai. The sample of porridge was asked to be tested by the bank, through the Anganwadi worker, the sample of porridge was sent to the District Women and Child Development Officer's Office, from where the sample was sent to the Food Testing Laboratory in Bombay for testing and this porridge was found to be of excellent quality. What was it that the bank had approved a loan and grant of Rs. 2 lakh 12 thousand to the group to start their own business. After estimating the amount according to his requirement, Mooh got one lakh 20 thousand rupees from the bank and started his business from November 2000. For the first time, 26 quintals of nutritional food was supplied by the group at the rate of Rs. 1196 per quintal, due to which every member started getting work for 15 days in a month and after repayment of bank loan, there was a daily income of Rs. 50. This process continued continuously and in the last 14 months, 22 tonnes of porridge has been supplied by the Jagrut Mahila Bachat Group as per the supply orders received by the Women and Child Development Department.",
    content3:"Oatmeal is procured by the Women and Child Development Department at the rate of Rs. 1195 per quintal and an average expenditure of Rs. 800 per quintal is incurred in construction, thus the group has earned a net income of Rs. 88000 so far, in which the group has earned Rs. 28800 of, repays the bank loan and divides the remaining amount among themselves. Treasurer Mrs. Ram Bai Kushwaha calculates the transactions of the amount. Smt. Kushwaha told that she purchases wheat and soyabean for making porridge and polythene for packing from the nearest market budhar and herself maintains the register of income and expenditure and pass book of each member. Shramti Rambai Kushwaha, secretary of the committee, told that the supply order On receipt, all of us women do the work of cleaning and packing the raw material regularly after doing household chores and disposing of it. And we get the work of threshing of wheat and soyabean done from the mill at the rate of 50 paise per kg. With this, each member gets work for 15 days and gets an average daily profit of Rs. 40 to 50. The members said that they are saving regularly and at present Rs. 10140.00 is deposited in the account of the group. He also told that all of us members use the savings amount to take loans as per their requirement and return them within the prescribed period with 2 percent monthly interest rate. All the women were very happy that now we do not have to depend on our husbands for savings, and now all of us women have also been able to contribute financially in the running of the family."
  },
  
  
]
export default PageData;